version: '3.3'

services: 
  web:
    image: node:16.13.0
    ports:
      - 80:80
    environment:
      - http_proxy
      - https_proxy
      - PORT=80
      - HOST=0.0.0.0
    working_dir: /src
    volumes:
      - .:/src
    restart: unless-stopped
    command: "npm run serve"