version: '3.3'

services: 
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    ports:
      - 80:80
    environment:
      - PORT=80
      - HOST=0.0.0.0
    restart: unless-stopped