
name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run generate
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publich_branch: gh-pages # The branch the action should deploy to.
          publish_dir: ./dist # The folder the action should deploy.